In [2]:
import pandas as pd

In [3]:
df1 = pd.read_excel("C:/Users/sneha/Downloads/Data_for_Clustering.xlsx")

In [4]:
df1.head()

,Country,Country Code,Arable land,Crop production index,Exports of goods and services (% of GDP),External balance on goods and services (% of GDP),"Foreign direct investment, net inflows (% of GDP)",GDP per capita (constant 2015 US$),GDP per capita growth (annual %),"GNI per capita, PPP (current international $)",...,Imports of goods and services (annual % growth),"Industry (including construction), value added (% of GDP)","International tourism, receipts (% of total exports)","Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)",Net ODA received (% of GNI),"Population ages 15-64, total",Population growth (annual %),Rural population (% of total population),"Unemployment, youth total (% of total labor force ages 15-24) (national estimate)",HDI
0,Albania,ALB,21.070560,50.556667,13.813751,-22.461537,2.500649,1662.045681,7.366358,3196.666667,...,18.812549,17.352575,42.328113,61.815000,9.265130,1.946905e+06,-0.627448,59.678333,NaN,0.626667
1,Angola,AGO,2.406353,21.466667,NaN,NaN,13.927988,1863.931676,4.145943,2640.000000,...,NaN,64.810202,0.657043,77.362000,6.878206,7.711915e+06,3.284100,52.877667,NaN,NaN
2,Armenia,ARM,15.776841,44.390000,21.560647,-33.300111,5.054413,1080.256730,6.541218,2211.666667,...,-2.940893,NaN,9.062739,62.835000,12.288509,2.046424e+06,-1.045806,34.636500,NaN,0.633333
3,Bangladesh,BGD,64.519475,52.873333,11.158615,-5.382907,0.263155,600.823836,2.955782,1440.000000,...,13.759608,22.407234,NaN,58.367333,1.997820,7.109893e+07,1.850753,77.365833,8.875,0.415000
4,Barbados,BRB,36.434109,235.710000,44.777714,-1.760037,1.621879,15512.384802,3.014745,11310.000000,...,NaN,15.352929,57.395875,67.877667,0.196341,1.752078e+05,0.186500,65.314333,28.506,0.731667

In [5]:
from sklearn.preprocessing import StandardScaler

cols_for_standardization = df1.columns[2:]  # standardizing the columns for better results

scaler = StandardScaler()

standardized_data = scaler.fit_transform(df1[cols_for_standardization])

standardized_df = pd.DataFrame(standardized_data, columns=cols_for_standardization)

non_standardized_df = df1[['Country', 'Country Code']]

df1 = pd.concat([non_standardized_df, standardized_df], axis=1)  # to get the final dataframe after standardization

In [6]:
df1.head()

,Country,Country Code,Arable land,Crop production index,Exports of goods and services (% of GDP),External balance on goods and services (% of GDP),"Foreign direct investment, net inflows (% of GDP)",GDP per capita (constant 2015 US$),GDP per capita growth (annual %),"GNI per capita, PPP (current international $)",...,Imports of goods and services (annual % growth),"Industry (including construction), value added (% of GDP)","International tourism, receipts (% of total exports)","Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)",Net ODA received (% of GNI),"Population ages 15-64, total",Population growth (annual %),Rural population (% of total population),"Unemployment, youth total (% of total labor force ages 15-24) (national estimate)",HDI
0,Albania,ALB,0.403198,-0.669026,-1.191531,-1.739468,-0.171557,-0.541066,1.920400,-0.377339,...,1.633170,-0.961351,1.797220,0.006501,0.474479,-0.245765,-1.629744,0.273911,NaN,0.608979
1,Angola,AGO,-0.880469,-1.577435,NaN,NaN,3.598988,-0.463929,0.747298,-0.583026,...,NaN,4.212347,-1.145317,1.748145,0.124907,-0.192768,1.400088,-0.092147,NaN,NaN
2,Armenia,ARM,0.039112,-0.861596,-0.734833,-2.909492,0.671078,-0.763356,1.619826,-0.741295,...,-1.521190,NaN,-0.551762,0.120766,0.917261,-0.244850,-1.953798,-1.074011,NaN,0.667356
3,Bangladesh,BGD,3.391482,-0.596682,-1.348058,0.104171,-0.909837,-0.946538,0.313758,-1.026425,...,0.900468,-0.410307,NaN,-0.379721,-0.589838,0.389934,0.289837,1.225973,-1.010810,-1.244492
4,Barbados,BRB,1.459856,5.112856,0.633870,0.495260,-0.461515,4.750886,0.335236,2.620530,...,NaN,-1.179347,2.861207,0.685668,-0.853670,-0.262052,-0.999271,0.577279,0.780099,1.528417

In [7]:
# performing KNN MEans imputation for the missing values with 5 neighbours


from sklearn.impute import KNNImputer

cols_for_imputation = df1.columns[2:]  
knn_imputer = KNNImputer(n_neighbors=5)

df1[cols_for_imputation] = knn_imputer.fit_transform(df1[cols_for_imputation])

In [8]:
df1.head()

,Country,Country Code,Arable land,Crop production index,Exports of goods and services (% of GDP),External balance on goods and services (% of GDP),"Foreign direct investment, net inflows (% of GDP)",GDP per capita (constant 2015 US$),GDP per capita growth (annual %),"GNI per capita, PPP (current international $)",...,Imports of goods and services (annual % growth),"Industry (including construction), value added (% of GDP)","International tourism, receipts (% of total exports)","Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)",Net ODA received (% of GNI),"Population ages 15-64, total",Population growth (annual %),Rural population (% of total population),"Unemployment, youth total (% of total labor force ages 15-24) (national estimate)",HDI
0,Albania,ALB,0.403198,-0.669026,-1.191531,-1.739468,-0.171557,-0.541066,1.920400,-0.377339,...,1.633170,-0.961351,1.797220,0.006501,0.474479,-0.245765,-1.629744,0.273911,-0.239235,0.608979
1,Angola,AGO,-0.880469,-1.577435,0.338833,-0.245572,3.598988,-0.463929,0.747298,-0.583026,...,-0.797649,4.212347,-1.145317,1.748145,0.124907,-0.192768,1.400088,-0.092147,-0.336944,-0.047763
2,Armenia,ARM,0.039112,-0.861596,-0.734833,-2.909492,0.671078,-0.763356,1.619826,-0.741295,...,-1.521190,-0.541822,-0.551762,0.120766,0.917261,-0.244850,-1.953798,-1.074011,0.142195,0.667356
3,Bangladesh,BGD,3.391482,-0.596682,-1.348058,0.104171,-0.909837,-0.946538,0.313758,-1.026425,...,0.900468,-0.410307,-0.297217,-0.379721,-0.589838,0.389934,0.289837,1.225973,-1.010810,-1.244492
4,Barbados,BRB,1.459856,5.112856,0.633870,0.495260,-0.461515,4.750886,0.335236,2.620530,...,0.047857,-1.179347,2.861207,0.685668,-0.853670,-0.262052,-0.999271,0.577279,0.780099,1.528417

In [9]:
# to perform hierarchical clustering 4 times and to drop the countries belonging to clusters with less than 4 countries

from scipy.cluster.hierarchy import linkage, fcluster
from collections import Counter
import numpy as np

np.random.seed(42)

df2 = pd.DataFrame(columns=df1.columns)   # to keep the dropped countries in this new empty dataframe

num_iterations = 4

for i in range(num_iterations):

    cols_for_clustering = df1.columns[2:] 
   
    linkage_matrix = linkage(df1[cols_for_clustering], metric='mahalanobis')   # Perform hierarchical clustering with mahalanobis distance
 
    outlier_threshold = 5   # defining a threshold for identifying outliers

    clusters = fcluster(linkage_matrix, t=outlier_threshold, criterion='distance')

    df1_copy = df1.copy()

    df1_copy['Cluster'] = clusters     # Now, 'df1' contains the cluster assignments for each country, taking into account the weights

    cluster_counts = Counter(df1_copy['Cluster'])   # Count the number of countries in each cluster

   
    small_clusters = [cluster for cluster, count in cluster_counts.items() if count < 4]    # Identifying clusters with fewer than 4 countries

    for cluster in small_clusters:
        country_codes_to_drop = df1_copy[df1_copy['Cluster'] == cluster]['Country Code'].tolist()
        print(f"Iteration {i+1}: Country Codes in Cluster {cluster} to be dropped: {', '.join(country_codes_to_drop)}")

        df2 = pd.concat([df2, df1_copy[df1_copy['Country Code'].isin(country_codes_to_drop)]], ignore_index=True)

   
    df1_copy = df1_copy[~df1_copy['Cluster'].isin(small_clusters)]    # Dropping countries belonging to small clusters

    df1_copy.drop(columns=['Cluster'], inplace=True)

    df1 = df1_copy

Iteration 1: Country Codes in Cluster 6 to be dropped: AGO
Iteration 1: Country Codes in Cluster 7 to be dropped: BRB
Iteration 1: Country Codes in Cluster 1 to be dropped: CHN
Iteration 1: Country Codes in Cluster 5 to be dropped: COD
Iteration 1: Country Codes in Cluster 4 to be dropped: GEO
Iteration 1: Country Codes in Cluster 8 to be dropped: GNB
Iteration 1: Country Codes in Cluster 2 to be dropped: IND
Iteration 2: Country Codes in Cluster 2 to be dropped: ARM
Iteration 2: Country Codes in Cluster 8 to be dropped: CPV
Iteration 2: Country Codes in Cluster 3 to be dropped: COG
Iteration 2: Country Codes in Cluster 6 to be dropped: GUY
Iteration 2: Country Codes in Cluster 7 to be dropped: JOR
Iteration 2: Country Codes in Cluster 5 to be dropped: SLB
Iteration 2: Country Codes in Cluster 4 to be dropped: ZMB
Iteration 3: Country Codes in Cluster 6 to be dropped: BRA
Iteration 3: Country Codes in Cluster 3 to be dropped: FJI
Iteration 3: Country Codes in Cluster 5 to be dropped: HTI
Iteration 3: Country Codes in Cluster 4 to be dropped: PNG
Iteration 3: Country Codes in Cluster 2 to be dropped: TJK
Iteration 4: Country Codes in Cluster 3 to be dropped: MMR
Iteration 4: Country Codes in Cluster 2 to be dropped: PAN

In [11]:
# performimg the KNN Means to identify 5 clusters after dropping the outliers

from sklearn.cluster import KMeans
import pandas as pd


np.random.seed(42)

numeric_cols = df1.drop(columns=['Country', 'Country Code'])

kmeans = KMeans(n_clusters=5)

kmeans.fit(numeric_cols)

cluster_labels = kmeans.labels_  # Get cluster labels for each data point

df1['Cluster'] = cluster_labels  # Adding cluster labels to the DataFrame

c:\Users\sneha\.ipynb_checkpoints\.conda\lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

In [12]:
df1.head()

,Country,Country Code,Arable land,Crop production index,Exports of goods and services (% of GDP),External balance on goods and services (% of GDP),"Foreign direct investment, net inflows (% of GDP)",GDP per capita (constant 2015 US$),GDP per capita growth (annual %),"GNI per capita, PPP (current international $)",...,"Industry (including construction), value added (% of GDP)","International tourism, receipts (% of total exports)","Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)",Net ODA received (% of GNI),"Population ages 15-64, total",Population growth (annual %),Rural population (% of total population),"Unemployment, youth total (% of total labor force ages 15-24) (national estimate)",HDI,Cluster
0,Albania,ALB,0.403198,-0.669026,-1.191531,-1.739468,-0.171557,-0.541066,1.920400,-0.377339,...,-0.961351,1.797220,0.006501,0.474479,-0.245765,-1.629744,0.273911,-0.239235,0.608979,2
3,Bangladesh,BGD,3.391482,-0.596682,-1.348058,0.104171,-0.909837,-0.946538,0.313758,-1.026425,...,-0.410307,-0.297217,-0.379721,-0.589838,0.389934,0.289837,1.225973,-1.010810,-1.244492,3
5,Belize,BLZ,-0.854505,0.477597,0.514909,0.580315,-0.100212,0.768652,-0.052436,0.759487,...,-0.550274,0.948758,-0.374176,-0.525422,-0.262546,1.334472,-0.026487,0.900389,0.448442,1
6,Benin,BEN,0.252187,-0.645709,-0.514864,0.022087,-1.001653,-0.853663,0.085435,-0.981470,...,-1.226026,-0.280614,1.140132,0.501853,-0.233050,1.008562,0.423451,-0.488380,-1.609349,0
7,Bolivia,BOL,-0.862383,-0.605114,-0.816046,-0.212793,1.951615,-0.424545,-0.119011,-0.425989,...,0.064021,-0.595754,1.004508,0.273647,-0.221310,0.282840,-0.810735,-1.210372,0.156557,0

In [195]:
# Now that the clusters are identified, the  assignment of the countries according to their clusters is done manually on the excel sheet to get the data for regrression ready.

# the cluster 0 has been names Cluster 1 in the final data for regression, Cluster 1 as 2 and so on.

# the outliers are put in Cluster 6

array([2, 3, 1, 0, 4])